config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :teachers

  authenticated :teacher do
    root to: 'students#index', as: :authenticated_root
  end

  devise_scope :teacher do
    root to: 'devise/sessions#new'
    get 'teachers/sign_out' => 'devise/sessions#destroy'
  end

  resources :students do
    member do
      post 'perform_simple_job', to: 'students#perform_simple_job'
      post 'perform_sidekiq_job', to: 'students#perform_sidekiq_job'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, :subject, :marks, presence: true
  validates :marks, numericality: { greater_than_or_equal_to: 0 }

  # Custom method to handle the new student creation or updating the marks if student exists
  def self.create_or_update_student(student_params)
    student = Student.find_by(name: student_params[:name], subject: student_params[:subject])

    if student
      # Update the marks by adding the new marks to the existing marks
      student.marks += student_params[:marks].to_i
      if student.save
        student
      else
        nil
      end
    else
      # If no student found, create a new record
      student = Student.new(student_params)
      student.save ? student : nil
    end
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    # if resource.admin?
    #   admin_dashboard_path
    # else
    #   teacher_dashboard_path
    # end
    students_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :get_student, only: [ :show, :edit, :update, :destroy, :perform_simple_job, :perform_sidekiq_job ]

  def index
    @students = Student.all
  end

  def show; end

  def new
    @student = Student.new
  end

  def create
    # Use the custom create_or_update_student method
    @student = Student.create_or_update_student(student_params)

    if @student
      flash[:notice] = 'Student successfully created or updated.'
      redirect_to students_path
    else
      flash[:alert] = 'There was an error processing the student details.'
      render :new
    end
  end

  def edit; end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      render json: @student, status: :ok
    else
      render json: { errors: @student.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @student.destroy
    flash[:notice] = 'Student successfully deleted.'
    redirect_to students_path
  end

  def perform_simple_job
    # SimpleJob.perform_later(@student, 11, "Afzal Rahman") --> basic job without time mentioned
    SimpleJob.set(wait: 30.seconds).perform_later(@student, 11, 'Afzal Rahman')
  end

  def perform_sidekiq_job
    SimpleSidekiqJob.perform_async(@student.name, 11, 'Afzal Rahman')
    SimpleSidekiqJob.perform_async(@student.name, 12, 'Afzal Rahman12')
    SimpleSidekiqJob.perform_async(@student.name, 13, 'Afzal Rahman13')
    SimpleSidekiqJob.perform_async(@student.name, 14, 'Afzal Rahman14')
    SimpleSidekiqJob.perform_async(@student.name, 15, 'Afzal Rahman15')
    SimpleSidekiqJob.perform_async(@student.name, 16, 'Afzal Rahman16')
    SimpleSidekiqJob.perform_async(@student.name, 17, 'Afzal Rahman17')
    SimpleSidekiqJob.perform_async(@student.name, 18, 'Afzal Rahman18')
    SimpleSidekiqJob.perform_async(@student.name, 19, 'Afzal Rahman19')
  end

  private

  def get_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :subject, :marks)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teacher Portal</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload" %> <!-- Ensure JavaScript is loaded -->

  <% if devise_controller? %>
    <%= stylesheet_link_tag 'devise', media: 'all', 'data-turbo-track': 'reload' %>
  <% end %>
    <%= javascript_importmap_tags %>
</head>

<body>
  <% flash.each do |key, message| %>
    <div class="flash <%= key %>" data-controller="flash" data-flash-key="<%= key %>">
      <%= message %>
    </div>
  <% end %>

  <header>
    <nav>
      <ul class="nav-list">
        <li><%= link_to "Home", authenticated_root_path, class: "btn btn-home" %></li>
        <% if teacher_signed_in? %>
          <li><%= link_to "Sign Out", destroy_teacher_session_path, method: :delete, class: "btn btn-logout" %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  
  <%= yield %>
</body>
</html>

app/views/students/edit.html.erb
<div class="edit-student">
  <h1>Edit Student</h1>

  <%= form_with model: @student, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, required: true %>
    </div>

    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, required: true %>
    </div>

    <div class="form-group">
      <%= f.label :marks %>
      <%= f.number_field :marks, required: true %>
    </div>

    <div class="form-actions">
      <%= f.submit "Update", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/students/index.html.erb
<div class="student-listing" data-controller="students">
  <h1>Student Listing</h1>
  
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Subject</th>
        <th>Marks</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr id="student-<%= student.id %>">
          <td>
            <span class="student-name" data-student-id="<%= student.id %>"><%= student.name %></span>
            <input type="text" class="edit-name" data-student-id="<%= student.id %>" value="<%= student.name %>" style="display: none;">
          </td>
          <td>
            <span class="student-subject" data-student-id="<%= student.id %>"><%= student.subject %></span>
            <input type="text" class="edit-subject" data-student-id="<%= student.id %>" value="<%= student.subject %>" style="display: none;">
          </td>
          <td>
            <span class="student-marks" data-student-id="<%= student.id %>"><%= student.marks %></span>
            <input type="number" class="edit-marks" data-student-id="<%= student.id %>" value="<%= student.marks %>" style="display: none;">
          </td>
          <td>
            <%= link_to "View", student_path(student), class: "btn btn-view" %>
            <button class="btn-edit" data-student-id="<%= student.id %>">Edit</button>
            <button class="btn-save" data-student-id="<%= student.id %>" style="display: none;">Save</button>
            <button class="btn-cancel" data-student-id="<%= student.id %>" style="display: none;">Cancel</button>
            <%= link_to "Delete", student_path(student), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-delete" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="add-student">
  <%= link_to "Add New Student", new_student_path, class: "btn btn-primary" %>
</div>

app/views/students/new.html.erb
<div class="new-student">
  <h1>Add New Student</h1>

  <%= form_with model: @student, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, required: true %>
    </div>

    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, required: true %>
    </div>

    <div class="form-group">
      <%= f.label :marks %>
      <%= f.number_field :marks, required: true %>
    </div>

    <div class="form-actions">
      <%= f.submit "Add Student", class: "btn btn-primary" %>
      <%= link_to "Back", authenticated_root_path, class: "btn btn-home" %>
    </div>
  <% end %>
</div>

app/views/students/show.html.erb
<div class="student-details" data-controller="student-show">
  <h1>Student Details</h1>

  <table>
    <tr>
      <th>Name:</th>
      <td><%= @student.name %></td>
    </tr>
    <tr>
      <th>Subject:</th>
      <td><%= @student.subject %></td>
    </tr>
    <tr>
      <th>Marks:</th>
      <td><%= @student.marks %></td>
    </tr>
  </table>

  <div class="actions">
    <%= link_to "Edit", edit_student_path(@student), class: "btn btn-edit" %>
    <%= link_to "Back to List", students_path, class: "btn btn-primary" %>
    <%= link_to "Delete", student_path(@student), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-delete" %>
  </div>
</div>  
  
<div class="add-student">
  <%= link_to "Perform Simple Job", perform_simple_job_student_path(@student), class: "btn btn-secondary", data: {turbo_method: :post} %>
</div>
<div class="add-student">
  <%= link_to "Perform Sidekiq Job", perform_sidekiq_job_student_path(@student), class: "btn custom-btn-job", data: {turbo_method: :post} %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the Teacher Portal</h1>
<p>Please log in to manage students.</p>